version: "3.5"
networks:
  mysql:
  back:
services:
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: r00t
  server:
    build:
      context: ./backend
    depends_on:
      - db
    container_name: backend
    volumes:
      - ./backend:/backend
    networks:
      - mysql
    ports:
      - 9090:9090
    restart: on-failure:5
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - mysql
  front:
    depends_on:
      - server
    #fix from https://github.com/Software-For-Love/template-react-app-docker/commit/a6a5606dcbe16a46ddf6c20e8e71e38d9ec4dbd0
    stdin_open: true
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3003:3000
    networks:
      - mysql