version: '3.5'
services:
  db:
    image: mysql:5.7
    container_name: database
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      #MYSQL_HOST: 127.0.0.1
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: db
  server:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/server
    ports:
      - 9090:9090
  # front:
  #   depends_on:
  #     - db
  #   #fix from https://github.com/Software-For-Love/template-react-app-docker/commit/a6a5606dcbe16a46ddf6c20e8e71e38d9ec4dbd0
  #   stdin_open: true
  #   build:
  #     context: ./frontend
  #   container_name: frontend
  #   volumes:
  #     - ./frontend:/app
  #     - ./frontend/node_modules/:/app/node_modules
  #   ports:
  #     - 3003:3000
